
create view dwh_compose1.source.Agreement as
SELECT [AgreementID]
      ,[PolicyNumber]
      ,[ReportingLOB]
      ,[SourceCompanyCode]
      ,[CompanyCodeCode]
      ,[CompanyCodeDesc]
      ,[AdministrationStatusCode]
      ,[SourceIssuingState]
      ,[IssuingStatueCode]
      ,[IssuingStateDesc]
      ,[SourceBillingFrequencyCode]
      ,[BillingFrequencyCode]
      ,[BillingFrequencyDesc]
      ,[SourceBillingTypeCode]
      ,[BillingTypeCode]
      ,[BillingTypeDesc]
      ,[PaidToDate]
      ,[BillToDate]
      ,[IssuedDate]
      ,[PremiumRefundAmount]
      ,[ExpirationDate]
      ,[PaymentAmount]
      ,[PaymentDueDate]
      ,[SourceProductCode]
      ,[SourceProductDescription]
      ,[Duration]
      ,[ProductMortalityCode]
      ,[ProductMortalityDescription]
      ,[PolicyStatusModifiedDate]
      ,[AgreementValue]
      ,[AgreementValueDate]
      ,[LastPaymentDate]
      ,[LastPaymentAmount]
      ,[DeathBenefit]
      ,[LoanPayoffAmount]
      ,[SourceSystemCode]
      ,[SourceSystemName]
FROM [src_NextGen].[source].[Agreement]

union

SELECT [AgreementID]
      ,[PolicyNumber]
      ,[ReportingLOB]
      ,[SourceCompanyCode]
      ,[CompanyCodeCode]
      ,[CompanyCodeDesc]
      ,[AdministrationStatusCode]
      ,[SourceIssuingState]
      ,[IssuingStatueCode]
      ,[IssuingStateDesc]
      ,[SourceBillingFrequencyCode]
      ,[BillingFrequencyCode]
      ,[BillingFrequencyDesc]
      ,[SourceBillingTypeCode]
      ,[BillingTypeCode]
      ,[BillingTypeDesc]
      ,[PaidToDate]
      ,[BillToDate]
      ,[IssuedDate]
      ,[PremiumRefundAmount]
      ,[ExpirationDate]
      ,[PaymentAmount]
      ,[PaymentDueDate]
      ,[SourceProductCode]
      ,[SourceProductDescription]
      ,[Duration]
      ,[ProductMortalityCode]
      ,[ProductMortalityDescription]
      ,[PolicyStatusModifiedDate]
      ,[AgreementValue]
      ,[AgreementValueDate]
      ,[LastPaymentDate]
      ,[LastPaymentAmount]
      ,[DeathBenefit]
      ,[LoanPayoffAmount]
      ,[SourceSystemCode]
      ,[SourceSystemName]
FROM [src_ADMI].[source].[Agreement]

union

SELECT [AgreementID]
      ,[PolicyNumber]
      ,[ReportingLOB]
      ,[SourceCompanyCode]
      ,[CompanyCodeCode]
      ,[CompanyCodeDesc]
      ,[AdministrationStatusCode]
      ,[SourceIssuingState]
      ,[IssuingStatueCode]
      ,[IssuingStateDesc]
      ,[SourceBillingFrequencyCode]
      ,[BillingFrequencyCode]
      ,[BillingFrequencyDesc]
      ,[SourceBillingTypeCode]
      ,[BillingTypeCode]
      ,[BillingTypeDesc]
      ,[PaidToDate]
      ,[BillToDate]
      ,[IssuedDate]
      ,[PremiumRefundAmount]
      ,[ExpirationDate]
      ,[PaymentAmount]
      ,[PaymentDueDate]
      ,[SourceProductCode]
      ,[SourceProductDescription]
      ,[Duration]
      ,[ProductMortalityCode]
      ,[ProductMortalityDescription]
      ,[PolicyStatusModifiedDate]
      ,[AgreementValue]
      ,[AgreementValueDate]
      ,[LastPaymentDate]
      ,[LastPaymentAmount]
      ,[DeathBenefit]
      ,[LoanPayoffAmount]
      ,[SourceSystemCode]
      ,[SourceSystemName]
FROM [src_IMS].[source].[Agreement]